
def motif(s, t):
    positions = []
    left = 0
    right = left + len(t)

    while right < len(s):
        if s[left : right] == t:
            positions.append(left + 1)
        left += 1
        right += 1

    return positions


s = 'GAGATGGCATGTCTGGCATGTCGGCATGTCCCCTGGCATGTGGCATGTCGTGGCATGTATTCAGGCATGTTAGTGCGGCATGTATCGGGCATGTTATAGGCATGTTGGCATGTCGGCATGTGCGGCATGTACCGGCATGTCCTTGGGCATGTAGGCATGTGGCATGTCGTGGCATGTAACCCGTGGGCATGTATAATAGGCATGTGGCATGTGGCATGTGGCATGTCCCGGCATGTCGGCATGTTCCGGGCATGTTCTGGGCATGTAGGCATGTGTGGCATGTGGCATGTATAGGTCGGCATGTGAAGGCATGTTGGCATGTCGGCATGTGAGTGGGCATGTCGGCATGTCGGCATGTGCGGCATGTGGCATGTGGCATGTGGCATGTAGGCATGTGGCATGTCTCATTGATGGCATGTCCGGCATGTAACGGCATGTAAGCCAAGGCATGTGTCTAAGGCATGTAGGCATGTTGGCATGTGGCATGTCGGGCATGTCTGACGTGGCATGTATGGCATGTTCAAGGGCATGTAAAGGCATGTGGCATGTGGCATGTAATGTCATGGCATGTTATAGGGGGCGGCATGTGGGCATGTGTGTCGGCATGTTGCCCGGCGGCATGTGGCATGTGGCATGTGGCAGACGCATTATAGATCGAGTTTAGGCATGTGGCATGTCCAGGCATGTGGCATGTAGGCATGTGTGGCATGTCGGCATGTTGAGTGGCATGTGGCATGTGCGGCATGTCTACCGGCATGTTTAATACGGCATGTAGGCATGTGTGGCATGTCCACCGGCATGTGGCATGTGGCATGTCGGCATGTGCGGCATGT' 
t = 'GGCATGTGG'
print(motif(s, t))

# output = [35, 154, 199, 206, 213, 277, 361, 368, 375, 390, 475, 536, 543, 582, 617, 624, 631, 664, 681, 725, 796, 803]