
def inferring_mrna(protein):
    mod = 1000000
    codons_for_amino_acid = {
        'A': 4, 'C': 2, 'D': 2, 'E': 2, 'F': 2, 'G': 4, 
        'H': 2, 'I': 3, 'K': 2, 'L': 6, 'M': 1, 'N': 2, 
        'P': 4, 'Q': 2, 'R': 6, 'S': 6, 'T': 4, 'V': 4, 
        'W': 1, 'Y': 2, 'Stop': 3}
    
    total_rna_strings = codons_for_amino_acid['Stop']

    for aa in protein:
        total_rna_strings = (total_rna_strings * codons_for_amino_acid[aa]) % mod
    return total_rna_strings


print(inferring_mrna('MEDYYIEYHKMGEVATPQKRQAPTHDNSTIDYAQWEDASNCFMLCCAASDSDHEIPFPMMSFEETKKAEVMQVNHHADKVETKNLNKQLIHSTELIGQRFTHTPYLASYCMNISYYSECHPWLWCHCNCMCNVAWAQCEKRQNWFQLHSPIRGRSVVFMWDDKIQSHWGMNYWDADSLKHVNWCFHGIDWFQFYGHPKDKWRWDLFLPHGFCMAVSRSTAIPYFFTQCIMYMGRQKPDREVTFFQPYHSRKAICMSFFSCREGCLSWRPGGHHVWWAEKYYWIGQCKINGHDFPLCKAGSMIRSAISEDCHFMDFQFAPYMLVMADSFYAPLMGEENLPPLTYIWMSIWQMWYLHKTLKMWCTPPHMPSANYTDECMNNFMCKPYMTVMPTVTGATCLCFNSMVDLMIVHGKKVVCKTRSTFLTVWWVKNCWCWDLLTRGGKYILPQKNSTPHRYMWLQWCFFDPPDHYVRGYMQSRLLSFHEGYRGWFWNFTEACFYCCADYIHFHATITYLYCSPFIVSAFYYYHYCIHEREEAGAISPPIPLYRLEVYHRDEFWARPDVTVHIESENVIIVEDPPMDQARYCCYEWTVCHMVAGMWPHGEERVEPAKQQTPDRFTTGCHHHLNWEYDLVHYIRKLKLLRTRQIRAGTCLHTVKMCFDANWEHKQMNGMDDEMFFDPPERYKTPNWHSGAGDQYNTDATFTRHPRCEINMHHMQRGHWHADAYVDFCWFNMHWVWVMELSPHAFVTTEACNSMYNFQATAHAHKPGSFWIPLGQLWGFWERCIFLAWFCIDNEQAWAKLHQYRWLEQMGQMICEQGRTFLTCKAWHMQCQFGSAKAVWEVRNNVPDMIPITCSMWLCCDFPQLKPPMHPYLTIDACYVVKEGNDTNVQKQWTQQYPYIFTAMYTCYIMCKIIFWFWMWTMDMRKQMDEWVISDNYWLWEDSDNNSLPRRKWFHRAVIYDDWANNHHPKFNLNERVDKNAGANHHPSWNNLHHCLITQK'))